# Generated by Django 5.1.3 on 2024-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rasgo_1', models.CharField(max_length=200)),
                ('rasgo_2', models.CharField(max_length=200)),
                ('coste', models.IntegerField()),
                ('imagen', models.FileField(upload_to='campeones/')),
            ],
        ),
    ]
